// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package top.rslly.iot.utility.exhook;

public interface BrokerInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emqx.exhook.v2.BrokerInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string version = 1;</code>
   */
  String getVersion();
  /**
   * <code>string version = 1;</code>
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>string sysdescr = 2;</code>
   */
  String getSysdescr();
  /**
   * <code>string sysdescr = 2;</code>
   */
  com.google.protobuf.ByteString
      getSysdescrBytes();

  /**
   * <code>int64 uptime = 3;</code>
   */
  long getUptime();

  /**
   * <code>string datetime = 4;</code>
   */
  String getDatetime();
  /**
   * <code>string datetime = 4;</code>
   */
  com.google.protobuf.ByteString
      getDatetimeBytes();
}
