// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package top.rslly.iot.utility.exhook;

public interface ClientConnackRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emqx.exhook.v2.ClientConnackRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.emqx.exhook.v2.ConnInfo conninfo = 1;</code>
   */
  boolean hasConninfo();
  /**
   * <code>.emqx.exhook.v2.ConnInfo conninfo = 1;</code>
   */
  ConnInfo getConninfo();
  /**
   * <code>.emqx.exhook.v2.ConnInfo conninfo = 1;</code>
   */
  ConnInfoOrBuilder getConninfoOrBuilder();

  /**
   * <code>string result_code = 2;</code>
   */
  String getResultCode();
  /**
   * <code>string result_code = 2;</code>
   */
  com.google.protobuf.ByteString
      getResultCodeBytes();

  /**
   * <code>repeated .emqx.exhook.v2.Property props = 3;</code>
   */
  java.util.List<Property>
      getPropsList();
  /**
   * <code>repeated .emqx.exhook.v2.Property props = 3;</code>
   */
  Property getProps(int index);
  /**
   * <code>repeated .emqx.exhook.v2.Property props = 3;</code>
   */
  int getPropsCount();
  /**
   * <code>repeated .emqx.exhook.v2.Property props = 3;</code>
   */
  java.util.List<? extends PropertyOrBuilder>
      getPropsOrBuilderList();
  /**
   * <code>repeated .emqx.exhook.v2.Property props = 3;</code>
   */
  PropertyOrBuilder getPropsOrBuilder(
      int index);

  /**
   * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
   */
  boolean hasMeta();
  /**
   * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
   */
  RequestMeta getMeta();
  /**
   * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
   */
  RequestMetaOrBuilder getMetaOrBuilder();
}
