// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package top.rslly.iot.utility.exhook;

public interface ClientSubscribeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emqx.exhook.v2.ClientSubscribeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.emqx.exhook.v2.ClientInfo clientinfo = 1;</code>
   */
  boolean hasClientinfo();
  /**
   * <code>.emqx.exhook.v2.ClientInfo clientinfo = 1;</code>
   */
  ClientInfo getClientinfo();
  /**
   * <code>.emqx.exhook.v2.ClientInfo clientinfo = 1;</code>
   */
  ClientInfoOrBuilder getClientinfoOrBuilder();

  /**
   * <code>repeated .emqx.exhook.v2.Property props = 2;</code>
   */
  java.util.List<Property>
      getPropsList();
  /**
   * <code>repeated .emqx.exhook.v2.Property props = 2;</code>
   */
  Property getProps(int index);
  /**
   * <code>repeated .emqx.exhook.v2.Property props = 2;</code>
   */
  int getPropsCount();
  /**
   * <code>repeated .emqx.exhook.v2.Property props = 2;</code>
   */
  java.util.List<? extends PropertyOrBuilder>
      getPropsOrBuilderList();
  /**
   * <code>repeated .emqx.exhook.v2.Property props = 2;</code>
   */
  PropertyOrBuilder getPropsOrBuilder(
      int index);

  /**
   * <code>repeated .emqx.exhook.v2.TopicFilter topic_filters = 3;</code>
   */
  java.util.List<TopicFilter>
      getTopicFiltersList();
  /**
   * <code>repeated .emqx.exhook.v2.TopicFilter topic_filters = 3;</code>
   */
  TopicFilter getTopicFilters(int index);
  /**
   * <code>repeated .emqx.exhook.v2.TopicFilter topic_filters = 3;</code>
   */
  int getTopicFiltersCount();
  /**
   * <code>repeated .emqx.exhook.v2.TopicFilter topic_filters = 3;</code>
   */
  java.util.List<? extends TopicFilterOrBuilder>
      getTopicFiltersOrBuilderList();
  /**
   * <code>repeated .emqx.exhook.v2.TopicFilter topic_filters = 3;</code>
   */
  TopicFilterOrBuilder getTopicFiltersOrBuilder(
      int index);

  /**
   * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
   */
  boolean hasMeta();
  /**
   * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
   */
  RequestMeta getMeta();
  /**
   * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
   */
  RequestMetaOrBuilder getMetaOrBuilder();
}
