// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package top.rslly.iot.utility.exhook;

public interface ConnInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emqx.exhook.v2.ConnInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string node = 1;</code>
   */
  String getNode();
  /**
   * <code>string node = 1;</code>
   */
  com.google.protobuf.ByteString
      getNodeBytes();

  /**
   * <code>string clientid = 2;</code>
   */
  String getClientid();
  /**
   * <code>string clientid = 2;</code>
   */
  com.google.protobuf.ByteString
      getClientidBytes();

  /**
   * <code>string username = 3;</code>
   */
  String getUsername();
  /**
   * <code>string username = 3;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string peerhost = 4;</code>
   */
  String getPeerhost();
  /**
   * <code>string peerhost = 4;</code>
   */
  com.google.protobuf.ByteString
      getPeerhostBytes();

  /**
   * <code>uint32 sockport = 5;</code>
   */
  int getSockport();

  /**
   * <code>string proto_name = 6;</code>
   */
  String getProtoName();
  /**
   * <code>string proto_name = 6;</code>
   */
  com.google.protobuf.ByteString
      getProtoNameBytes();

  /**
   * <code>string proto_ver = 7;</code>
   */
  String getProtoVer();
  /**
   * <code>string proto_ver = 7;</code>
   */
  com.google.protobuf.ByteString
      getProtoVerBytes();

  /**
   * <code>uint32 keepalive = 8;</code>
   */
  int getKeepalive();
}
