// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package top.rslly.iot.utility.exhook;

public interface EmptySuccessOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emqx.exhook.v2.EmptySuccess)
    com.google.protobuf.MessageOrBuilder {
}
