// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package top.rslly.iot.utility.exhook;

public interface HookSpecOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emqx.exhook.v2.HookSpec)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The registered hooks name
   * Available value:
   *   "client.connect",      "client.connack"
   *   "client.connected",    "client.disconnected"
   *   "client.authenticate", "client.authorize"
   *   "client.subscribe",    "client.unsubscribe"
   *   "session.created",      "session.subscribed"
   *   "session.unsubscribed", "session.resumed"
   *   "session.discarded",    "session.takenover"
   *   "session.terminated"
   *   "message.publish", "message.delivered"
   *   "message.acked",   "message.dropped"
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <pre>
   * The registered hooks name
   * Available value:
   *   "client.connect",      "client.connack"
   *   "client.connected",    "client.disconnected"
   *   "client.authenticate", "client.authorize"
   *   "client.subscribe",    "client.unsubscribe"
   *   "session.created",      "session.subscribed"
   *   "session.unsubscribed", "session.resumed"
   *   "session.discarded",    "session.takenover"
   *   "session.terminated"
   *   "message.publish", "message.delivered"
   *   "message.acked",   "message.dropped"
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * The topic filters for message hooks
   * </pre>
   *
   * <code>repeated string topics = 2;</code>
   */
  java.util.List<String>
      getTopicsList();
  /**
   * <pre>
   * The topic filters for message hooks
   * </pre>
   *
   * <code>repeated string topics = 2;</code>
   */
  int getTopicsCount();
  /**
   * <pre>
   * The topic filters for message hooks
   * </pre>
   *
   * <code>repeated string topics = 2;</code>
   */
  String getTopics(int index);
  /**
   * <pre>
   * The topic filters for message hooks
   * </pre>
   *
   * <code>repeated string topics = 2;</code>
   */
  com.google.protobuf.ByteString
      getTopicsBytes(int index);
}
