// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package top.rslly.iot.utility.exhook;

public interface LoadedResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emqx.exhook.v2.LoadedResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .emqx.exhook.v2.HookSpec hooks = 1;</code>
   */
  java.util.List<HookSpec>
      getHooksList();
  /**
   * <code>repeated .emqx.exhook.v2.HookSpec hooks = 1;</code>
   */
  HookSpec getHooks(int index);
  /**
   * <code>repeated .emqx.exhook.v2.HookSpec hooks = 1;</code>
   */
  int getHooksCount();
  /**
   * <code>repeated .emqx.exhook.v2.HookSpec hooks = 1;</code>
   */
  java.util.List<? extends HookSpecOrBuilder>
      getHooksOrBuilderList();
  /**
   * <code>repeated .emqx.exhook.v2.HookSpec hooks = 1;</code>
   */
  HookSpecOrBuilder getHooksOrBuilder(
      int index);
}
