// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package top.rslly.iot.utility.exhook;

public interface ProviderUnloadedRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emqx.exhook.v2.ProviderUnloadedRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.emqx.exhook.v2.RequestMeta meta = 1;</code>
   */
  boolean hasMeta();
  /**
   * <code>.emqx.exhook.v2.RequestMeta meta = 1;</code>
   */
  RequestMeta getMeta();
  /**
   * <code>.emqx.exhook.v2.RequestMeta meta = 1;</code>
   */
  RequestMetaOrBuilder getMetaOrBuilder();
}
