// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package top.rslly.iot.utility.exhook;

public interface ProviderLoadedRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emqx.exhook.v2.ProviderLoadedRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.emqx.exhook.v2.BrokerInfo broker = 1;</code>
   */
  boolean hasBroker();
  /**
   * <code>.emqx.exhook.v2.BrokerInfo broker = 1;</code>
   */
  BrokerInfo getBroker();
  /**
   * <code>.emqx.exhook.v2.BrokerInfo broker = 1;</code>
   */
  BrokerInfoOrBuilder getBrokerOrBuilder();

  /**
   * <code>.emqx.exhook.v2.RequestMeta meta = 2;</code>
   */
  boolean hasMeta();
  /**
   * <code>.emqx.exhook.v2.RequestMeta meta = 2;</code>
   */
  RequestMeta getMeta();
  /**
   * <code>.emqx.exhook.v2.RequestMeta meta = 2;</code>
   */
  RequestMetaOrBuilder getMetaOrBuilder();
}
