// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package top.rslly.iot.utility.exhook;

public interface RequestMetaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emqx.exhook.v2.RequestMeta)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string node = 1;</code>
   */
  String getNode();
  /**
   * <code>string node = 1;</code>
   */
  com.google.protobuf.ByteString
      getNodeBytes();

  /**
   * <code>string version = 2;</code>
   */
  String getVersion();
  /**
   * <code>string version = 2;</code>
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>string sysdescr = 3;</code>
   */
  String getSysdescr();
  /**
   * <code>string sysdescr = 3;</code>
   */
  com.google.protobuf.ByteString
      getSysdescrBytes();

  /**
   * <code>string cluster_name = 4;</code>
   */
  String getClusterName();
  /**
   * <code>string cluster_name = 4;</code>
   */
  com.google.protobuf.ByteString
      getClusterNameBytes();
}
