// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package top.rslly.iot.utility.exhook;

public interface SessionSubscribedRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emqx.exhook.v2.SessionSubscribedRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.emqx.exhook.v2.ClientInfo clientinfo = 1;</code>
   */
  boolean hasClientinfo();
  /**
   * <code>.emqx.exhook.v2.ClientInfo clientinfo = 1;</code>
   */
  ClientInfo getClientinfo();
  /**
   * <code>.emqx.exhook.v2.ClientInfo clientinfo = 1;</code>
   */
  ClientInfoOrBuilder getClientinfoOrBuilder();

  /**
   * <code>string topic = 2;</code>
   */
  String getTopic();
  /**
   * <code>string topic = 2;</code>
   */
  com.google.protobuf.ByteString
      getTopicBytes();

  /**
   * <code>.emqx.exhook.v2.SubOpts subopts = 3;</code>
   */
  boolean hasSubopts();
  /**
   * <code>.emqx.exhook.v2.SubOpts subopts = 3;</code>
   */
  SubOpts getSubopts();
  /**
   * <code>.emqx.exhook.v2.SubOpts subopts = 3;</code>
   */
  SubOptsOrBuilder getSuboptsOrBuilder();

  /**
   * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
   */
  boolean hasMeta();
  /**
   * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
   */
  RequestMeta getMeta();
  /**
   * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
   */
  RequestMetaOrBuilder getMetaOrBuilder();
}
