// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package top.rslly.iot.utility.exhook;

public interface TopicFilterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emqx.exhook.v2.TopicFilter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>uint32 qos = 2;</code>
   */
  int getQos();
}
