// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package top.rslly.iot.utility.exhook;

public interface ValuedResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emqx.exhook.v2.ValuedResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.emqx.exhook.v2.ValuedResponse.ResponsedType type = 1;</code>
   */
  int getTypeValue();
  /**
   * <code>.emqx.exhook.v2.ValuedResponse.ResponsedType type = 1;</code>
   */
  ValuedResponse.ResponsedType getType();

  /**
   * <pre>
   * Boolean result, used on the 'client.authenticate', 'client.authorize' hooks
   * </pre>
   *
   * <code>bool bool_result = 3;</code>
   */
  boolean getBoolResult();

  /**
   * <pre>
   * Message result, used on the 'message.*' hooks
   * </pre>
   *
   * <code>.emqx.exhook.v2.Message message = 4;</code>
   */
  boolean hasMessage();
  /**
   * <pre>
   * Message result, used on the 'message.*' hooks
   * </pre>
   *
   * <code>.emqx.exhook.v2.Message message = 4;</code>
   */
  Message getMessage();
  /**
   * <pre>
   * Message result, used on the 'message.*' hooks
   * </pre>
   *
   * <code>.emqx.exhook.v2.Message message = 4;</code>
   */
  MessageOrBuilder getMessageOrBuilder();

  public ValuedResponse.ValueCase getValueCase();
}
